[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "objr-py"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = ["pandas", "openpyxl"]
classifiers = [
    "License :: OSI Approved :: MIT License",
]
